spring:
  profiles:
   active: dev
---
server:
  port: 8201
spring:
  profiles: dev #开发环境
  application:
    name: microservice-config-client
client:
  instance:
    instance-id: microservice-config8201 #默认名称修改
    prefer-ip-address: true #访问路径可以显示IP地址
  register-with-eureka: true #是否注册
  fetch-registry: true
  service-url:
    defaultZone: http://eureka7001.com:7001/eureka/

---
server:
  port: 8202
spring:
  profiles: test #测试环境
  application:
    name: microservice-config-client
client:
  instance:
    instance-id: microservice-config8202 #默认名称修改
    prefer-ip-address: true #访问路径可以显示IP地址
  register-with-eureka: true #是否注册
  fetch-registry: true
  service-url:
    defaultZone: http://eureka7001.com:7001/eureka/
